### ISSUE TITLE
Add support for stats on queued data writes

### ISSUE THREAD

**Issue by louiscryan** [python-hyper/draft-http2-debug-state#3]
Finding streams that are blocked on flow-control requires knowing that a stream has data that it wants to write

**Comment by Lukasa** [comment]
I certainly don't object to doing that. I think this will very much need to be optional because it's possible that the question makes no sense (e.g. if you're serving files you probably aren't "queueing" writes in a meaningful sense: you'll write as long as you have space in the window, and then wait until that window reopens).

**Comment by louiscryan** [comment]
I think optional is fine. I think the distinction you mention is key one, writers which produce bytes based on open flow control and writers which produce bytes which then have to wait for flow control.

I think there are likely to be more of the former than the latter but I agree there will be plenty of both.

**Comment by Lukasa** [comment]
Now in the current working copy.
